''
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../themes";
import ContextProvider from '@/context';
import Layout from "@/layouts";

export const metadata: Metadata = {
  title: "Format Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <ContextProvider>
        <ThemeProvider theme={theme}>
          <body>
            <Layout>
              {children}
            </Layout>
          </body>
        </ThemeProvider>
      </ContextProvider>
    </html>
  );
}
